name: 返利网

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * *"
    watch:
        types: [started]

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: npm install
              run: |
                  npm install
            - name: "运行【返利网】"
              run: |
                  node flw.js
              env:
                  FL_flwURL: ${{ secrets.FL_flwURL }}
                  FL_flwHEADER: ${{ secrets.FL_flwHEADER }}
                  FL_flwspBODY: ${{ secrets.FL_flwspBODY }}
                  FL_flwqwBODY: ${{ secrets.FL_flwqwBODY }}
                  PUSH_KEY: ${{ secrets.PUSH_KEY }}
