name: 惠头条

on:
  workflow_dispatch:
  watch:
    types: started
  schedule:
    - cron: '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/mantou5050/zaqi.git ~/zaqi
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【惠头条】'
        run: |
          node huitoutiao.js
